# Default initial positions for robot's ros2_control fake system

initial_positions:
  finger_joint: 0
  joint_1: -1.6156513
  joint_2: -0.09616764
  joint_3: 2.2113322
  joint_4: -0.5290093
  joint_5: 1.569051
  joint_6: -0.07592182